/* global document */

export function queryElements() {
  return {
    status: document.querySelector('#connection-status'),
    connection: document.querySelector('.connection'),
    streamCaption: document.querySelector('#stream-caption'),
    gitStatus: document.querySelector('#git-status'),
    streamLines: document.querySelector('#stream-lines'),
    streamEmpty: document.querySelector('#stream-empty'),
    jumpLatest: document.querySelector('#jump-latest'),
    projectSelector: document.querySelector('#project-selector'),
    scopePath: document.querySelector('#scope-path'),
    sessionBar: document.querySelector('#session-bar'),
    sessionPresets: document.querySelector('#session-presets'),
    composeForm: document.querySelector('#compose-form'),
    composeInput: document.querySelector('#compose-input'),
    composeSend: document.querySelector('#compose-send'),
    composeNote: document.querySelector('#compose-note'),
    voiceRecord: document.querySelector('#voice-record'),
    projectAdd: document.querySelector('#add-project'),
    projectFormShell: document.querySelector('#add-project-form'),
    projectForm: document.querySelector('#project-form'),
    projectPath: document.querySelector('#project-path'),
    projectDescription: document.querySelector('#project-description'),
    projectDetect: document.querySelector('#detect-project'),
    projectSave: document.querySelector('#save-project'),
    projectCancel: document.querySelector('#cancel-project'),
    projectStatus: document.querySelector('#project-status'),
    projectProposals: document.querySelector('#project-proposals'),
    managedProjects: document.querySelector('#managed-projects'),
    hostStats: document.querySelector('#host-stats'),
    hostRefresh: document.querySelector('#host-refresh'),
    hostCap: document.querySelector('#host-cap'),
    hostCapApply: document.querySelector('#host-cap-apply'),
    hostStatus: document.querySelector('#host-status'),
    tokenState: document.querySelector('#token-state'),
    token: document.querySelector('#capability-token'),
    harness: document.querySelector('#default-harness'),
    historyToggle: document.querySelector('#history-toggle'),
    historyDrawer: document.querySelector('#history-drawer'),
    historyClose: document.querySelector('#history-close'),
    historyScroll: document.querySelector('#history-scroll'),
    historySearch: document.querySelector('#history-search'),
    historyProjectFilter: document.querySelector('#history-project-filter'),
    liveHistory: document.querySelector('#live-history'),
    machineHistory: document.querySelector('#machine-history'),
    settingsToggle: document.querySelector('#settings-toggle'),
    settingsDrawer: document.querySelector('#settings-drawer'),
    settingsClose: document.querySelector('#settings-close'),
  };
}
